[package]
name = "asterisk-queue-handler-events"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
futures = "0.3.31"
iced = "0.13.1"
tokio = { version = "1.48.0", features = ["full"] }
